<?php

// code for ACF field group_5f726949e2c0a
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5f726949e2c0a',
	'title' => 'Manage Items',
	'fields' => array(
		array(
			'key' => 'field_5f726ce660135',
			'label' => 'IMPORTANT NOTE',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'Type the title for your item in the field above <i class="fas fa-arrow-circle-up"></i>. This will be the text displayed to link to it. <strong>Please be sure to assign one or more categories to your item at right.</strong>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5f726959cddce',
			'label' => 'Item Type',
			'name' => 'mgr_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'document' => 'Upload (document)',
				'video' => 'Video',
				'link' => 'Link',
				'resource' => 'Resource (link & img)',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'link',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5f726a5acddd0',
			'label' => 'Upload Document (or choose from Media Library)',
			'name' => 'mgr_file',
			'type' => 'file',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f726959cddce',
						'operator' => '==',
						'value' => 'document',
					),
				),
				array(
					array(
						'field' => 'field_5f726959cddce',
						'operator' => '==',
						'value' => 'resource',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f7270a3d641f',
			'label' => 'Video URL',
			'name' => 'mgr_url',
			'type' => 'text',
			'instructions' => 'Your library can manage items from Vimeo, YouTube, or Facebook. Make sure to include the <strong>https://</strong> or <strong>https://</strong> part of the URL.',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f726959cddce',
						'operator' => '==',
						'value' => 'vid',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f7270c9d6420',
			'label' => 'Link URL',
			'name' => 'mgr_url',
			'type' => 'text',
			'instructions' => 'Paste the link to whatever you\'re wanting to include in your Manager. Make sure that you include the <strong>http://</strong> or <strong>https://</strong> part. If you\'re linking to a video, please choose the VIDEO item type.',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f726959cddce',
						'operator' => '==',
						'value' => 'link',
					),
				),
				array(
					array(
						'field' => 'field_5f726959cddce',
						'operator' => '==',
						'value' => 'resource',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f9315a7f80c3',
			'label' => 'Author (optional)',
			'name' => 'mgr_author',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f726959cddce',
						'operator' => '==',
						'value' => 'resource',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5f9316aae9f70',
					'label' => 'Firstname',
					'name' => 'firstname',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f9316bde9f71',
					'label' => 'Lastname',
					'name' => 'lastname',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5f92fb28a8cef',
			'label' => 'Link text (optional)',
			'name' => 'mgr_vendor',
			'type' => 'text',
			'instructions' => 'vendor, i.e. Amazon or Advent<em>Source</em>',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f726959cddce',
						'operator' => '==',
						'value' => 'resource',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f726ee9f8053',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'OPTIONAL: Type a description of your item below <i class="fas fa-arrow-circle-down"></i>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'item',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'revisions',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'featured_image',
		10 => 'tags',
		11 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

endif;

??>